# ===== UWSM Check =====
exec-once = ~/.local/share/dotfiles/bin/check-uwsm

# ===== Theme/cursor settings =====
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# ===== Daemons/Services =====
# Managed by systemd user services (graphical-session.target)
# See: systemctl --user list-units --type=service