background = #121212
foreground = #BEBEBE

cursor-color = #EAEAEA
cursor-text = #121212

selection-background = #333333
selection-foreground = #EAEAEA

# normal colors
palette = 0=#1C1C1C
palette = 1=#FA6893
palette = 2=#F05585
palette = 3=#E64478
palette = 4=#CC3565
palette = 5=#FB7EA5
palette = 6=#FCA9C2
palette = 7=#FEE6EE

# bright colors
palette = 8=#3A3A3A
palette = 9=#FB7EA5
palette = 10=#FC8FB0
palette = 11=#FDA6C0
palette = 12=#FDBCD0
palette = 13=#FED1DF
palette = 14=#FEE4EC
palette = 15=#FFF3F7
