[config]

[templates.btop]
input_path = "~/.config/matugen/templates/btop.theme.tmpl"
output_path = '~/.local/share/dotfiles/themes/matugen/btop.theme'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty.conf'
output_path = '~/.local/share/dotfiles/themes/matugen/ghostty.conf'

[templates.gtk]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.local/share/dotfiles/themes/matugen/gtk.css'

[templates.dunst]
input_path = "~/.config/matugen/templates/dunstrc.tmpl"
output_path = "~/.config/dunst/dunstrc"

[templates.nvim]
input_path = '~/.config/matugen/templates/neovim.tmpl'
output_path = '~/.local/share/dotfiles/themes/matugen/neovim.lua'

